package com.dayday.maoYanFilm.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Film {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.film_id
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private Integer filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.film_name
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private String filmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.film_type1
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private String filmType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.film_type2
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private String filmType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.film_type3
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private String filmType3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.film_area
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private String filmArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.film_duration
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private Integer filmDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.film_time
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private Date filmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.film_location
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private String filmLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.film_reputation
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private BigDecimal filmReputation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.film_population
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private Integer filmPopulation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_id
     *
     * @return the value of film.film_id
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Integer getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_id
     *
     * @param filmId the value for film.film_id
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmId(Integer filmId) {
        this.filmId = filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_name
     *
     * @return the value of film.film_name
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public String getFilmName() {
        return filmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_name
     *
     * @param filmName the value for film.film_name
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmName(String filmName) {
        this.filmName = filmName == null ? null : filmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_type1
     *
     * @return the value of film.film_type1
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public String getFilmType1() {
        return filmType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_type1
     *
     * @param filmType1 the value for film.film_type1
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmType1(String filmType1) {
        this.filmType1 = filmType1 == null ? null : filmType1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_type2
     *
     * @return the value of film.film_type2
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public String getFilmType2() {
        return filmType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_type2
     *
     * @param filmType2 the value for film.film_type2
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmType2(String filmType2) {
        this.filmType2 = filmType2 == null ? null : filmType2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_type3
     *
     * @return the value of film.film_type3
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public String getFilmType3() {
        return filmType3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_type3
     *
     * @param filmType3 the value for film.film_type3
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmType3(String filmType3) {
        this.filmType3 = filmType3 == null ? null : filmType3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_area
     *
     * @return the value of film.film_area
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public String getFilmArea() {
        return filmArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_area
     *
     * @param filmArea the value for film.film_area
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmArea(String filmArea) {
        this.filmArea = filmArea == null ? null : filmArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_duration
     *
     * @return the value of film.film_duration
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Integer getFilmDuration() {
        return filmDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_duration
     *
     * @param filmDuration the value for film.film_duration
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmDuration(Integer filmDuration) {
        this.filmDuration = filmDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_time
     *
     * @return the value of film.film_time
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Date getFilmTime() {
        return filmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_time
     *
     * @param filmTime the value for film.film_time
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmTime(Date filmTime) {
        this.filmTime = filmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_location
     *
     * @return the value of film.film_location
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public String getFilmLocation() {
        return filmLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_location
     *
     * @param filmLocation the value for film.film_location
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmLocation(String filmLocation) {
        this.filmLocation = filmLocation == null ? null : filmLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_reputation
     *
     * @return the value of film.film_reputation
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public BigDecimal getFilmReputation() {
        return filmReputation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_reputation
     *
     * @param filmReputation the value for film.film_reputation
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmReputation(BigDecimal filmReputation) {
        this.filmReputation = filmReputation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_population
     *
     * @return the value of film.film_population
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Integer getFilmPopulation() {
        return filmPopulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_population
     *
     * @param filmPopulation the value for film.film_population
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmPopulation(Integer filmPopulation) {
        this.filmPopulation = filmPopulation;
    }
}