package com.dayday.maoYanFilm.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FilmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public FilmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFilmIdIsNull() {
            addCriterion("film_id is null");
            return (Criteria) this;
        }

        public Criteria andFilmIdIsNotNull() {
            addCriterion("film_id is not null");
            return (Criteria) this;
        }

        public Criteria andFilmIdEqualTo(Integer value) {
            addCriterion("film_id =", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdNotEqualTo(Integer value) {
            addCriterion("film_id <>", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdGreaterThan(Integer value) {
            addCriterion("film_id >", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("film_id >=", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdLessThan(Integer value) {
            addCriterion("film_id <", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdLessThanOrEqualTo(Integer value) {
            addCriterion("film_id <=", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdIn(List<Integer> values) {
            addCriterion("film_id in", values, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdNotIn(List<Integer> values) {
            addCriterion("film_id not in", values, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdBetween(Integer value1, Integer value2) {
            addCriterion("film_id between", value1, value2, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("film_id not between", value1, value2, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmNameIsNull() {
            addCriterion("film_name is null");
            return (Criteria) this;
        }

        public Criteria andFilmNameIsNotNull() {
            addCriterion("film_name is not null");
            return (Criteria) this;
        }

        public Criteria andFilmNameEqualTo(String value) {
            addCriterion("film_name =", value, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmNameNotEqualTo(String value) {
            addCriterion("film_name <>", value, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmNameGreaterThan(String value) {
            addCriterion("film_name >", value, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmNameGreaterThanOrEqualTo(String value) {
            addCriterion("film_name >=", value, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmNameLessThan(String value) {
            addCriterion("film_name <", value, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmNameLessThanOrEqualTo(String value) {
            addCriterion("film_name <=", value, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmNameLike(String value) {
            addCriterion("film_name like", value, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmNameNotLike(String value) {
            addCriterion("film_name not like", value, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmNameIn(List<String> values) {
            addCriterion("film_name in", values, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmNameNotIn(List<String> values) {
            addCriterion("film_name not in", values, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmNameBetween(String value1, String value2) {
            addCriterion("film_name between", value1, value2, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmNameNotBetween(String value1, String value2) {
            addCriterion("film_name not between", value1, value2, "filmName");
            return (Criteria) this;
        }

        public Criteria andFilmType1IsNull() {
            addCriterion("film_type1 is null");
            return (Criteria) this;
        }

        public Criteria andFilmType1IsNotNull() {
            addCriterion("film_type1 is not null");
            return (Criteria) this;
        }

        public Criteria andFilmType1EqualTo(String value) {
            addCriterion("film_type1 =", value, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType1NotEqualTo(String value) {
            addCriterion("film_type1 <>", value, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType1GreaterThan(String value) {
            addCriterion("film_type1 >", value, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType1GreaterThanOrEqualTo(String value) {
            addCriterion("film_type1 >=", value, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType1LessThan(String value) {
            addCriterion("film_type1 <", value, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType1LessThanOrEqualTo(String value) {
            addCriterion("film_type1 <=", value, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType1Like(String value) {
            addCriterion("film_type1 like", value, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType1NotLike(String value) {
            addCriterion("film_type1 not like", value, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType1In(List<String> values) {
            addCriterion("film_type1 in", values, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType1NotIn(List<String> values) {
            addCriterion("film_type1 not in", values, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType1Between(String value1, String value2) {
            addCriterion("film_type1 between", value1, value2, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType1NotBetween(String value1, String value2) {
            addCriterion("film_type1 not between", value1, value2, "filmType1");
            return (Criteria) this;
        }

        public Criteria andFilmType2IsNull() {
            addCriterion("film_type2 is null");
            return (Criteria) this;
        }

        public Criteria andFilmType2IsNotNull() {
            addCriterion("film_type2 is not null");
            return (Criteria) this;
        }

        public Criteria andFilmType2EqualTo(String value) {
            addCriterion("film_type2 =", value, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType2NotEqualTo(String value) {
            addCriterion("film_type2 <>", value, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType2GreaterThan(String value) {
            addCriterion("film_type2 >", value, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType2GreaterThanOrEqualTo(String value) {
            addCriterion("film_type2 >=", value, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType2LessThan(String value) {
            addCriterion("film_type2 <", value, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType2LessThanOrEqualTo(String value) {
            addCriterion("film_type2 <=", value, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType2Like(String value) {
            addCriterion("film_type2 like", value, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType2NotLike(String value) {
            addCriterion("film_type2 not like", value, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType2In(List<String> values) {
            addCriterion("film_type2 in", values, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType2NotIn(List<String> values) {
            addCriterion("film_type2 not in", values, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType2Between(String value1, String value2) {
            addCriterion("film_type2 between", value1, value2, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType2NotBetween(String value1, String value2) {
            addCriterion("film_type2 not between", value1, value2, "filmType2");
            return (Criteria) this;
        }

        public Criteria andFilmType3IsNull() {
            addCriterion("film_type3 is null");
            return (Criteria) this;
        }

        public Criteria andFilmType3IsNotNull() {
            addCriterion("film_type3 is not null");
            return (Criteria) this;
        }

        public Criteria andFilmType3EqualTo(String value) {
            addCriterion("film_type3 =", value, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmType3NotEqualTo(String value) {
            addCriterion("film_type3 <>", value, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmType3GreaterThan(String value) {
            addCriterion("film_type3 >", value, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmType3GreaterThanOrEqualTo(String value) {
            addCriterion("film_type3 >=", value, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmType3LessThan(String value) {
            addCriterion("film_type3 <", value, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmType3LessThanOrEqualTo(String value) {
            addCriterion("film_type3 <=", value, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmType3Like(String value) {
            addCriterion("film_type3 like", value, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmType3NotLike(String value) {
            addCriterion("film_type3 not like", value, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmType3In(List<String> values) {
            addCriterion("film_type3 in", values, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmType3NotIn(List<String> values) {
            addCriterion("film_type3 not in", values, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmType3Between(String value1, String value2) {
            addCriterion("film_type3 between", value1, value2, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmType3NotBetween(String value1, String value2) {
            addCriterion("film_type3 not between", value1, value2, "filmType3");
            return (Criteria) this;
        }

        public Criteria andFilmAreaIsNull() {
            addCriterion("film_area is null");
            return (Criteria) this;
        }

        public Criteria andFilmAreaIsNotNull() {
            addCriterion("film_area is not null");
            return (Criteria) this;
        }

        public Criteria andFilmAreaEqualTo(String value) {
            addCriterion("film_area =", value, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmAreaNotEqualTo(String value) {
            addCriterion("film_area <>", value, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmAreaGreaterThan(String value) {
            addCriterion("film_area >", value, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmAreaGreaterThanOrEqualTo(String value) {
            addCriterion("film_area >=", value, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmAreaLessThan(String value) {
            addCriterion("film_area <", value, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmAreaLessThanOrEqualTo(String value) {
            addCriterion("film_area <=", value, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmAreaLike(String value) {
            addCriterion("film_area like", value, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmAreaNotLike(String value) {
            addCriterion("film_area not like", value, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmAreaIn(List<String> values) {
            addCriterion("film_area in", values, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmAreaNotIn(List<String> values) {
            addCriterion("film_area not in", values, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmAreaBetween(String value1, String value2) {
            addCriterion("film_area between", value1, value2, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmAreaNotBetween(String value1, String value2) {
            addCriterion("film_area not between", value1, value2, "filmArea");
            return (Criteria) this;
        }

        public Criteria andFilmDurationIsNull() {
            addCriterion("film_duration is null");
            return (Criteria) this;
        }

        public Criteria andFilmDurationIsNotNull() {
            addCriterion("film_duration is not null");
            return (Criteria) this;
        }

        public Criteria andFilmDurationEqualTo(Integer value) {
            addCriterion("film_duration =", value, "filmDuration");
            return (Criteria) this;
        }

        public Criteria andFilmDurationNotEqualTo(Integer value) {
            addCriterion("film_duration <>", value, "filmDuration");
            return (Criteria) this;
        }

        public Criteria andFilmDurationGreaterThan(Integer value) {
            addCriterion("film_duration >", value, "filmDuration");
            return (Criteria) this;
        }

        public Criteria andFilmDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("film_duration >=", value, "filmDuration");
            return (Criteria) this;
        }

        public Criteria andFilmDurationLessThan(Integer value) {
            addCriterion("film_duration <", value, "filmDuration");
            return (Criteria) this;
        }

        public Criteria andFilmDurationLessThanOrEqualTo(Integer value) {
            addCriterion("film_duration <=", value, "filmDuration");
            return (Criteria) this;
        }

        public Criteria andFilmDurationIn(List<Integer> values) {
            addCriterion("film_duration in", values, "filmDuration");
            return (Criteria) this;
        }

        public Criteria andFilmDurationNotIn(List<Integer> values) {
            addCriterion("film_duration not in", values, "filmDuration");
            return (Criteria) this;
        }

        public Criteria andFilmDurationBetween(Integer value1, Integer value2) {
            addCriterion("film_duration between", value1, value2, "filmDuration");
            return (Criteria) this;
        }

        public Criteria andFilmDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("film_duration not between", value1, value2, "filmDuration");
            return (Criteria) this;
        }

        public Criteria andFilmTimeIsNull() {
            addCriterion("film_time is null");
            return (Criteria) this;
        }

        public Criteria andFilmTimeIsNotNull() {
            addCriterion("film_time is not null");
            return (Criteria) this;
        }

        public Criteria andFilmTimeEqualTo(Date value) {
            addCriterion("film_time =", value, "filmTime");
            return (Criteria) this;
        }

        public Criteria andFilmTimeNotEqualTo(Date value) {
            addCriterion("film_time <>", value, "filmTime");
            return (Criteria) this;
        }

        public Criteria andFilmTimeGreaterThan(Date value) {
            addCriterion("film_time >", value, "filmTime");
            return (Criteria) this;
        }

        public Criteria andFilmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("film_time >=", value, "filmTime");
            return (Criteria) this;
        }

        public Criteria andFilmTimeLessThan(Date value) {
            addCriterion("film_time <", value, "filmTime");
            return (Criteria) this;
        }

        public Criteria andFilmTimeLessThanOrEqualTo(Date value) {
            addCriterion("film_time <=", value, "filmTime");
            return (Criteria) this;
        }

        public Criteria andFilmTimeIn(List<Date> values) {
            addCriterion("film_time in", values, "filmTime");
            return (Criteria) this;
        }

        public Criteria andFilmTimeNotIn(List<Date> values) {
            addCriterion("film_time not in", values, "filmTime");
            return (Criteria) this;
        }

        public Criteria andFilmTimeBetween(Date value1, Date value2) {
            addCriterion("film_time between", value1, value2, "filmTime");
            return (Criteria) this;
        }

        public Criteria andFilmTimeNotBetween(Date value1, Date value2) {
            addCriterion("film_time not between", value1, value2, "filmTime");
            return (Criteria) this;
        }

        public Criteria andFilmLocationIsNull() {
            addCriterion("film_location is null");
            return (Criteria) this;
        }

        public Criteria andFilmLocationIsNotNull() {
            addCriterion("film_location is not null");
            return (Criteria) this;
        }

        public Criteria andFilmLocationEqualTo(String value) {
            addCriterion("film_location =", value, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmLocationNotEqualTo(String value) {
            addCriterion("film_location <>", value, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmLocationGreaterThan(String value) {
            addCriterion("film_location >", value, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmLocationGreaterThanOrEqualTo(String value) {
            addCriterion("film_location >=", value, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmLocationLessThan(String value) {
            addCriterion("film_location <", value, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmLocationLessThanOrEqualTo(String value) {
            addCriterion("film_location <=", value, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmLocationLike(String value) {
            addCriterion("film_location like", value, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmLocationNotLike(String value) {
            addCriterion("film_location not like", value, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmLocationIn(List<String> values) {
            addCriterion("film_location in", values, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmLocationNotIn(List<String> values) {
            addCriterion("film_location not in", values, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmLocationBetween(String value1, String value2) {
            addCriterion("film_location between", value1, value2, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmLocationNotBetween(String value1, String value2) {
            addCriterion("film_location not between", value1, value2, "filmLocation");
            return (Criteria) this;
        }

        public Criteria andFilmReputationIsNull() {
            addCriterion("film_reputation is null");
            return (Criteria) this;
        }

        public Criteria andFilmReputationIsNotNull() {
            addCriterion("film_reputation is not null");
            return (Criteria) this;
        }

        public Criteria andFilmReputationEqualTo(BigDecimal value) {
            addCriterion("film_reputation =", value, "filmReputation");
            return (Criteria) this;
        }

        public Criteria andFilmReputationNotEqualTo(BigDecimal value) {
            addCriterion("film_reputation <>", value, "filmReputation");
            return (Criteria) this;
        }

        public Criteria andFilmReputationGreaterThan(BigDecimal value) {
            addCriterion("film_reputation >", value, "filmReputation");
            return (Criteria) this;
        }

        public Criteria andFilmReputationGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("film_reputation >=", value, "filmReputation");
            return (Criteria) this;
        }

        public Criteria andFilmReputationLessThan(BigDecimal value) {
            addCriterion("film_reputation <", value, "filmReputation");
            return (Criteria) this;
        }

        public Criteria andFilmReputationLessThanOrEqualTo(BigDecimal value) {
            addCriterion("film_reputation <=", value, "filmReputation");
            return (Criteria) this;
        }

        public Criteria andFilmReputationIn(List<BigDecimal> values) {
            addCriterion("film_reputation in", values, "filmReputation");
            return (Criteria) this;
        }

        public Criteria andFilmReputationNotIn(List<BigDecimal> values) {
            addCriterion("film_reputation not in", values, "filmReputation");
            return (Criteria) this;
        }

        public Criteria andFilmReputationBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("film_reputation between", value1, value2, "filmReputation");
            return (Criteria) this;
        }

        public Criteria andFilmReputationNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("film_reputation not between", value1, value2, "filmReputation");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationIsNull() {
            addCriterion("film_population is null");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationIsNotNull() {
            addCriterion("film_population is not null");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationEqualTo(Integer value) {
            addCriterion("film_population =", value, "filmPopulation");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationNotEqualTo(Integer value) {
            addCriterion("film_population <>", value, "filmPopulation");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationGreaterThan(Integer value) {
            addCriterion("film_population >", value, "filmPopulation");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationGreaterThanOrEqualTo(Integer value) {
            addCriterion("film_population >=", value, "filmPopulation");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationLessThan(Integer value) {
            addCriterion("film_population <", value, "filmPopulation");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationLessThanOrEqualTo(Integer value) {
            addCriterion("film_population <=", value, "filmPopulation");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationIn(List<Integer> values) {
            addCriterion("film_population in", values, "filmPopulation");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationNotIn(List<Integer> values) {
            addCriterion("film_population not in", values, "filmPopulation");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationBetween(Integer value1, Integer value2) {
            addCriterion("film_population between", value1, value2, "filmPopulation");
            return (Criteria) this;
        }

        public Criteria andFilmPopulationNotBetween(Integer value1, Integer value2) {
            addCriterion("film_population not between", value1, value2, "filmPopulation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table film
     *
     * @mbggenerated do_not_delete_during_merge Sat Aug 12 15:50:47 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table film
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}