package com.dayday.maoYanFilm.pojo;

import java.math.BigDecimal;

public class Ticket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.film_id
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private Integer filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_plus_tip
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private Long ticketPlusTip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_except_tip
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private Long ticketExceptTip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_total
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private Long ticketTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_first_week
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private Long ticketFirstWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_showing_num
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private Integer ticketShowingNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_population_avg
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private BigDecimal ticketPopulationAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_presence_rate
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    private BigDecimal ticketPresenceRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.film_id
     *
     * @return the value of ticket.film_id
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Integer getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.film_id
     *
     * @param filmId the value for ticket.film_id
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setFilmId(Integer filmId) {
        this.filmId = filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_plus_tip
     *
     * @return the value of ticket.ticket_plus_tip
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Long getTicketPlusTip() {
        return ticketPlusTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_plus_tip
     *
     * @param ticketPlusTip the value for ticket.ticket_plus_tip
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setTicketPlusTip(Long ticketPlusTip) {
        this.ticketPlusTip = ticketPlusTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_except_tip
     *
     * @return the value of ticket.ticket_except_tip
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Long getTicketExceptTip() {
        return ticketExceptTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_except_tip
     *
     * @param ticketExceptTip the value for ticket.ticket_except_tip
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setTicketExceptTip(Long ticketExceptTip) {
        this.ticketExceptTip = ticketExceptTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_total
     *
     * @return the value of ticket.ticket_total
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Long getTicketTotal() {
        return ticketTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_total
     *
     * @param ticketTotal the value for ticket.ticket_total
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setTicketTotal(Long ticketTotal) {
        this.ticketTotal = ticketTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_first_week
     *
     * @return the value of ticket.ticket_first_week
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Long getTicketFirstWeek() {
        return ticketFirstWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_first_week
     *
     * @param ticketFirstWeek the value for ticket.ticket_first_week
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setTicketFirstWeek(Long ticketFirstWeek) {
        this.ticketFirstWeek = ticketFirstWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_showing_num
     *
     * @return the value of ticket.ticket_showing_num
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Integer getTicketShowingNum() {
        return ticketShowingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_showing_num
     *
     * @param ticketShowingNum the value for ticket.ticket_showing_num
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setTicketShowingNum(Integer ticketShowingNum) {
        this.ticketShowingNum = ticketShowingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_population_avg
     *
     * @return the value of ticket.ticket_population_avg
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public BigDecimal getTicketPopulationAvg() {
        return ticketPopulationAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_population_avg
     *
     * @param ticketPopulationAvg the value for ticket.ticket_population_avg
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setTicketPopulationAvg(BigDecimal ticketPopulationAvg) {
        this.ticketPopulationAvg = ticketPopulationAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_presence_rate
     *
     * @return the value of ticket.ticket_presence_rate
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public BigDecimal getTicketPresenceRate() {
        return ticketPresenceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_presence_rate
     *
     * @param ticketPresenceRate the value for ticket.ticket_presence_rate
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setTicketPresenceRate(BigDecimal ticketPresenceRate) {
        this.ticketPresenceRate = ticketPresenceRate;
    }
}