package com.dayday.maoYanFilm.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TicketExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public TicketExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFilmIdIsNull() {
            addCriterion("film_id is null");
            return (Criteria) this;
        }

        public Criteria andFilmIdIsNotNull() {
            addCriterion("film_id is not null");
            return (Criteria) this;
        }

        public Criteria andFilmIdEqualTo(Integer value) {
            addCriterion("film_id =", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdNotEqualTo(Integer value) {
            addCriterion("film_id <>", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdGreaterThan(Integer value) {
            addCriterion("film_id >", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("film_id >=", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdLessThan(Integer value) {
            addCriterion("film_id <", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdLessThanOrEqualTo(Integer value) {
            addCriterion("film_id <=", value, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdIn(List<Integer> values) {
            addCriterion("film_id in", values, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdNotIn(List<Integer> values) {
            addCriterion("film_id not in", values, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdBetween(Integer value1, Integer value2) {
            addCriterion("film_id between", value1, value2, "filmId");
            return (Criteria) this;
        }

        public Criteria andFilmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("film_id not between", value1, value2, "filmId");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipIsNull() {
            addCriterion("ticket_plus_tip is null");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipIsNotNull() {
            addCriterion("ticket_plus_tip is not null");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipEqualTo(Long value) {
            addCriterion("ticket_plus_tip =", value, "ticketPlusTip");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipNotEqualTo(Long value) {
            addCriterion("ticket_plus_tip <>", value, "ticketPlusTip");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipGreaterThan(Long value) {
            addCriterion("ticket_plus_tip >", value, "ticketPlusTip");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipGreaterThanOrEqualTo(Long value) {
            addCriterion("ticket_plus_tip >=", value, "ticketPlusTip");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipLessThan(Long value) {
            addCriterion("ticket_plus_tip <", value, "ticketPlusTip");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipLessThanOrEqualTo(Long value) {
            addCriterion("ticket_plus_tip <=", value, "ticketPlusTip");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipIn(List<Long> values) {
            addCriterion("ticket_plus_tip in", values, "ticketPlusTip");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipNotIn(List<Long> values) {
            addCriterion("ticket_plus_tip not in", values, "ticketPlusTip");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipBetween(Long value1, Long value2) {
            addCriterion("ticket_plus_tip between", value1, value2, "ticketPlusTip");
            return (Criteria) this;
        }

        public Criteria andTicketPlusTipNotBetween(Long value1, Long value2) {
            addCriterion("ticket_plus_tip not between", value1, value2, "ticketPlusTip");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipIsNull() {
            addCriterion("ticket_except_tip is null");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipIsNotNull() {
            addCriterion("ticket_except_tip is not null");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipEqualTo(Long value) {
            addCriterion("ticket_except_tip =", value, "ticketExceptTip");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipNotEqualTo(Long value) {
            addCriterion("ticket_except_tip <>", value, "ticketExceptTip");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipGreaterThan(Long value) {
            addCriterion("ticket_except_tip >", value, "ticketExceptTip");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipGreaterThanOrEqualTo(Long value) {
            addCriterion("ticket_except_tip >=", value, "ticketExceptTip");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipLessThan(Long value) {
            addCriterion("ticket_except_tip <", value, "ticketExceptTip");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipLessThanOrEqualTo(Long value) {
            addCriterion("ticket_except_tip <=", value, "ticketExceptTip");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipIn(List<Long> values) {
            addCriterion("ticket_except_tip in", values, "ticketExceptTip");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipNotIn(List<Long> values) {
            addCriterion("ticket_except_tip not in", values, "ticketExceptTip");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipBetween(Long value1, Long value2) {
            addCriterion("ticket_except_tip between", value1, value2, "ticketExceptTip");
            return (Criteria) this;
        }

        public Criteria andTicketExceptTipNotBetween(Long value1, Long value2) {
            addCriterion("ticket_except_tip not between", value1, value2, "ticketExceptTip");
            return (Criteria) this;
        }

        public Criteria andTicketTotalIsNull() {
            addCriterion("ticket_total is null");
            return (Criteria) this;
        }

        public Criteria andTicketTotalIsNotNull() {
            addCriterion("ticket_total is not null");
            return (Criteria) this;
        }

        public Criteria andTicketTotalEqualTo(Long value) {
            addCriterion("ticket_total =", value, "ticketTotal");
            return (Criteria) this;
        }

        public Criteria andTicketTotalNotEqualTo(Long value) {
            addCriterion("ticket_total <>", value, "ticketTotal");
            return (Criteria) this;
        }

        public Criteria andTicketTotalGreaterThan(Long value) {
            addCriterion("ticket_total >", value, "ticketTotal");
            return (Criteria) this;
        }

        public Criteria andTicketTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("ticket_total >=", value, "ticketTotal");
            return (Criteria) this;
        }

        public Criteria andTicketTotalLessThan(Long value) {
            addCriterion("ticket_total <", value, "ticketTotal");
            return (Criteria) this;
        }

        public Criteria andTicketTotalLessThanOrEqualTo(Long value) {
            addCriterion("ticket_total <=", value, "ticketTotal");
            return (Criteria) this;
        }

        public Criteria andTicketTotalIn(List<Long> values) {
            addCriterion("ticket_total in", values, "ticketTotal");
            return (Criteria) this;
        }

        public Criteria andTicketTotalNotIn(List<Long> values) {
            addCriterion("ticket_total not in", values, "ticketTotal");
            return (Criteria) this;
        }

        public Criteria andTicketTotalBetween(Long value1, Long value2) {
            addCriterion("ticket_total between", value1, value2, "ticketTotal");
            return (Criteria) this;
        }

        public Criteria andTicketTotalNotBetween(Long value1, Long value2) {
            addCriterion("ticket_total not between", value1, value2, "ticketTotal");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekIsNull() {
            addCriterion("ticket_first_week is null");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekIsNotNull() {
            addCriterion("ticket_first_week is not null");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekEqualTo(Long value) {
            addCriterion("ticket_first_week =", value, "ticketFirstWeek");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekNotEqualTo(Long value) {
            addCriterion("ticket_first_week <>", value, "ticketFirstWeek");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekGreaterThan(Long value) {
            addCriterion("ticket_first_week >", value, "ticketFirstWeek");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekGreaterThanOrEqualTo(Long value) {
            addCriterion("ticket_first_week >=", value, "ticketFirstWeek");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekLessThan(Long value) {
            addCriterion("ticket_first_week <", value, "ticketFirstWeek");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekLessThanOrEqualTo(Long value) {
            addCriterion("ticket_first_week <=", value, "ticketFirstWeek");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekIn(List<Long> values) {
            addCriterion("ticket_first_week in", values, "ticketFirstWeek");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekNotIn(List<Long> values) {
            addCriterion("ticket_first_week not in", values, "ticketFirstWeek");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekBetween(Long value1, Long value2) {
            addCriterion("ticket_first_week between", value1, value2, "ticketFirstWeek");
            return (Criteria) this;
        }

        public Criteria andTicketFirstWeekNotBetween(Long value1, Long value2) {
            addCriterion("ticket_first_week not between", value1, value2, "ticketFirstWeek");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumIsNull() {
            addCriterion("ticket_showing_num is null");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumIsNotNull() {
            addCriterion("ticket_showing_num is not null");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumEqualTo(Integer value) {
            addCriterion("ticket_showing_num =", value, "ticketShowingNum");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumNotEqualTo(Integer value) {
            addCriterion("ticket_showing_num <>", value, "ticketShowingNum");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumGreaterThan(Integer value) {
            addCriterion("ticket_showing_num >", value, "ticketShowingNum");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ticket_showing_num >=", value, "ticketShowingNum");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumLessThan(Integer value) {
            addCriterion("ticket_showing_num <", value, "ticketShowingNum");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumLessThanOrEqualTo(Integer value) {
            addCriterion("ticket_showing_num <=", value, "ticketShowingNum");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumIn(List<Integer> values) {
            addCriterion("ticket_showing_num in", values, "ticketShowingNum");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumNotIn(List<Integer> values) {
            addCriterion("ticket_showing_num not in", values, "ticketShowingNum");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumBetween(Integer value1, Integer value2) {
            addCriterion("ticket_showing_num between", value1, value2, "ticketShowingNum");
            return (Criteria) this;
        }

        public Criteria andTicketShowingNumNotBetween(Integer value1, Integer value2) {
            addCriterion("ticket_showing_num not between", value1, value2, "ticketShowingNum");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgIsNull() {
            addCriterion("ticket_population_avg is null");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgIsNotNull() {
            addCriterion("ticket_population_avg is not null");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgEqualTo(BigDecimal value) {
            addCriterion("ticket_population_avg =", value, "ticketPopulationAvg");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgNotEqualTo(BigDecimal value) {
            addCriterion("ticket_population_avg <>", value, "ticketPopulationAvg");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgGreaterThan(BigDecimal value) {
            addCriterion("ticket_population_avg >", value, "ticketPopulationAvg");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ticket_population_avg >=", value, "ticketPopulationAvg");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgLessThan(BigDecimal value) {
            addCriterion("ticket_population_avg <", value, "ticketPopulationAvg");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ticket_population_avg <=", value, "ticketPopulationAvg");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgIn(List<BigDecimal> values) {
            addCriterion("ticket_population_avg in", values, "ticketPopulationAvg");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgNotIn(List<BigDecimal> values) {
            addCriterion("ticket_population_avg not in", values, "ticketPopulationAvg");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ticket_population_avg between", value1, value2, "ticketPopulationAvg");
            return (Criteria) this;
        }

        public Criteria andTicketPopulationAvgNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ticket_population_avg not between", value1, value2, "ticketPopulationAvg");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateIsNull() {
            addCriterion("ticket_presence_rate is null");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateIsNotNull() {
            addCriterion("ticket_presence_rate is not null");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateEqualTo(BigDecimal value) {
            addCriterion("ticket_presence_rate =", value, "ticketPresenceRate");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateNotEqualTo(BigDecimal value) {
            addCriterion("ticket_presence_rate <>", value, "ticketPresenceRate");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateGreaterThan(BigDecimal value) {
            addCriterion("ticket_presence_rate >", value, "ticketPresenceRate");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ticket_presence_rate >=", value, "ticketPresenceRate");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateLessThan(BigDecimal value) {
            addCriterion("ticket_presence_rate <", value, "ticketPresenceRate");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ticket_presence_rate <=", value, "ticketPresenceRate");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateIn(List<BigDecimal> values) {
            addCriterion("ticket_presence_rate in", values, "ticketPresenceRate");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateNotIn(List<BigDecimal> values) {
            addCriterion("ticket_presence_rate not in", values, "ticketPresenceRate");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ticket_presence_rate between", value1, value2, "ticketPresenceRate");
            return (Criteria) this;
        }

        public Criteria andTicketPresenceRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ticket_presence_rate not between", value1, value2, "ticketPresenceRate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ticket
     *
     * @mbggenerated do_not_delete_during_merge Sat Aug 12 15:50:47 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ticket
     *
     * @mbggenerated Sat Aug 12 15:50:47 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}